# Generated by Django 4.1.3 on 2022-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
