# Generated by Django 4.1.3 on 2022-11-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_images',
            new_name='featured_image',
        ),
    ]
